slang_dict = {
    'smh': 'shake my head',
    'tbh': 'to be honest',
    'goat': 'greatest of all time',
    'lol': 'laugh out loud',
    'lmao': 'laugh my ass off',
    'lmfao': 'laugh my fucking ass off',
    'idk': 'i dont know',
    'mvp': 'most valuable player',
    'fmvp': 'finals most valuable player',
    'goated': 'greatest of all time',
    'nah': 'no way',
    'kinda': 'kind of',
    'ngl': 'not going to lie',
    'ass': 'bad',
    'plz': 'please',
    'fts': 'free throws',
    'pts': 'points',
    'gg': 'good game',
    'ffs': 'for fucks sake',
    'pt': 'point',
    'ft': 'free throws',
    'pls': 'please',
    'st': 'first',
    'nd': 'second',
    'rd': 'third',
    'th': 'fourth',
    'yea': 'yes',
    'yeah': 'yes',
    'yup': 'yes',
    'yep': 'yes',
    'imo': 'in my opinion',
    'idc': 'i dont care',
    'em': 'them',
    'mins': 'minutes',
    'refs': 'referees',
    'gotta': 'got to',
    'ikr': 'i know right',
    'wtf': 'what the fuck',
    'fr': 'for real',
    'vs': 'versus',
    'btw': 'by the way'
}
